### ISSUE TITLE
[依頼]　chat-spaceの挙動確認

### ISSUE THREAD

**Issue by fumito0808ajgj** [fumito0808ajgj/chat-space#7]
＃　ipアドレス

54.249.90.246

**Comment by kohei-isoda** [comment]
山岸さん、ご提出ありがとうございます！
頂いたIPアドレスなのですが、ChatSpaceではなくTECH::MASTERのIPアドレスであるようです。

再度ご自身のChatSpaceのIPアドレスを提出してください！
またお手数ですが、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kohei-isoda** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯ フラッシュメッセージが日本語設定されていない
[![Screenshot from Gyazo](https://gyazo.com/926f0328a012b7fb078b8bcce94acae8/raw)](https://gyazo.com/926f0328a012b7fb078b8bcce94acae8)

◯ ユーザー名が固定されている
（※ testというcurrent_userの名前が反映されていない）
[![Screenshot from Gyazo](https://gyazo.com/e768a765288b9d9da21c93aa4d74fb6d/raw)](https://gyazo.com/e768a765288b9d9da21c93aa4d74fb6d)

◯ ユーザー編集画面にcssが当たっていない
[![Screenshot from Gyazo](https://gyazo.com/a77110adb37ef47db0bed5b485f0ed86/raw)](https://gyazo.com/a77110adb37ef47db0bed5b485f0ed86)

◯ アイコンをクリックし遷移するページが間違えている
（※ 本来であれば歯車はユーザー編集ページ、ペンマークは新規グループ作成ページです）

◯ 新規グループ作成画面が崩れている（見本通りになっていない）
[![Screenshot from Gyazo](https://gyazo.com/a880c5968a318dedfc3dc1374ba249b5/raw)](https://gyazo.com/a880c5968a318dedfc3dc1374ba249b5)

◯ ユーザー検索が規定のインクリメンタルサーチではなくチェックボックスセレクトになっている

◯ メッセージ投稿画面下部のフォームに大きな余白が出来てしまっている
[![Screenshot from Gyazo](https://gyazo.com/37c3d8465b84998120936af80be7f73b/raw)](https://gyazo.com/37c3d8465b84998120936af80be7f73b)

◯ リロードした際に画面が崩れてしまう（見本通りになっていない）
[![Screenshot from Gyazo](https://gyazo.com/7a97dd877a0222f967b770bd94fa5767/raw)](https://gyazo.com/7a97dd877a0222f967b770bd94fa5767)

◯ メッセージの自動更新機能が動いていない

◯ ログアウトすることが出来ない

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
